spring.application.name=Backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Gmail Configuration
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=${MAIL_USERNAME:dummy_email@gmail.com}
# spring.mail.password=${MAIL_PASSWORD:}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# Mailpit Configuration
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false